language: ruby
rvm:
 - 2.7.1

services:
  - postgresql

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - nvm install --lts

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database jantar_para_dois_test;' -U postgres

script:
  - bundle exec rails webpacker:compile
  - bundle exec rake